# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java:
          - "11.0.18+10"
          - "17.0.7+7"
          - "18.0.2+9"
          - "19.0.1+10"
          - "20.0.1+9"
    name: Java ${{ matrix.Java }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "microsoft"
          java-version: ${{ matrix.java }}
      - run: java HelloWorld.java
